# automatically generated by the FlatBuffers compiler, do not modify

# namespace: serialization

class Action(object):
    ACTION_NIL = 0
    ACTION_LEFT = 1
    ACTION_DOWN = 2
    ACTION_RIGHT = 3
    ACTION_USE = 4
    ACTION_ESCAPE = 5

