# automatically generated by the FlatBuffers compiler, do not modify

# namespace: serialization

class Action(object):
    ACTION_NIL = 0
    ACTION_UP = 1
    ACTION_LEFT = 2
    ACTION_DOWN = 3
    ACTION_RIGHT = 4
    ACTION_USE = 5
    ACTION_ESCAPE = 6

