# automatically generated by the FlatBuffers compiler, do not modify

# namespace: serialization

import flatbuffers

class IntKeyValuePair(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsIntKeyValuePair(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntKeyValuePair()
        x.Init(buf, n + offset)
        return x

    # IntKeyValuePair
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntKeyValuePair
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # IntKeyValuePair
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def IntKeyValuePairStart(builder): builder.StartObject(2)
def IntKeyValuePairAddKey(builder, key): builder.PrependInt32Slot(0, key, 0)
def IntKeyValuePairAddValue(builder, value): builder.PrependInt32Slot(1, value, 0)
def IntKeyValuePairEnd(builder): return builder.EndObject()
