# automatically generated by the FlatBuffers compiler, do not modify

# namespace: serialization

import flatbuffers

class Vector2d(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsVector2d(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Vector2d()
        x.Init(buf, n + offset)
        return x

    # Vector2d
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vector2d
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Vector2d
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Vector2dStart(builder): builder.StartObject(2)
def Vector2dAddX(builder, x): builder.PrependFloat32Slot(0, x, 0.0)
def Vector2dAddY(builder, y): builder.PrependFloat32Slot(1, y, 0.0)
def Vector2dEnd(builder): return builder.EndObject()
