// automatically generated by the FlatBuffers compiler, do not modify

package qmul.gvgai.engine.core.game.serialization;

public final class Phase {
  private Phase() { }
  public static final int START = 0;
  public static final int INIT = 1;
  public static final int ACT = 2;
  public static final int ABORT = 3;
  public static final int END = 4;

  public static final String[] names = { "START", "INIT", "ACT", "ABORT", "END", };

  public static String name(int e) { return names[e]; }
}

