// automatically generated by the FlatBuffers compiler, do not modify

package core.game.serialization;

public final class Action {
  private Action() { }
  public static final int ACTION_NIL = 0;
  public static final int ACTION_UP = 1;
  public static final int ACTION_LEFT = 2;
  public static final int ACTION_DOWN = 3;
  public static final int ACTION_RIGHT = 4;
  public static final int ACTION_USE = 5;
  public static final int ACTION_ESCAPE = 6;

  public static final String[] names = { "ACTION_NIL", "ACTION_UP", "ACTION_LEFT", "ACTION_DOWN", "ACTION_RIGHT", "ACTION_USE", "ACTION_ESCAPE", };

  public static String name(int e) { return names[e]; }
}

