// automatically generated by the FlatBuffers compiler, do not modify

package qmul.gvgai.engine.core.game.serialization;

public final class Winner {
  private Winner() { }
  public static final int PLAYER_DISQ = -100;
  public static final int NO_WINNER = -1;
  public static final int PLAYER_LOSES = 0;
  public static final int PLAYER_WINS = 1;
}

