# automatically generated by the FlatBuffers compiler, do not modify

# namespace: serialization

class Winner(object):
    PLAYER_DISQ = -100
    NO_WINNER = -1
    PLAYER_LOSES = 0
    PLAYER_WINS = 1

